# default config.yml for Shortify by vemacs
# website: http://dev.bukkit.org/server-mods/shortify/
# sponsored by Nullblock
# available values for shortener are: googl, bitly, tinyurl, isgd, turlca
# the default shortener is isgd
# we do not recommend tinyurl because it has high latency
# for better uptime, use googl for the shortener
# to get your API key (NOT oAUTH), see 
# https://developers.google.com/url-shortener/v1/getting_started#auth
# under "Acquiring and using an API key"
# SHORTIFY WILL NOT WORK IF THE GOO.GL API KEY IS INVALID
# to use googl, change both shortener and googAPI values
# bit.ly is not recommended, as it is slow and downtime may be high
# bitlyUSER should be the username you use to sign on to bit.ly
# bitlyAPI value can be found at https://bitly.com/a/settings/advanced
# click "show legacy API key", and copy and paste the value into bitlyAPI
# turlca has received only minimal testing and may be very high-latency
shortener: isgd
googAPI: none
bitlyUSER: none
bitlyAPI: none
minlength: 20
# toggles if Shortify should automatically update
auto-update: true