name: Shortify
main: com.nullblock.vemacs.Shortify.Shortify
version: 1.3.0
description: The most advanced URL shortener for Bukkit. A fast and configurable plugin that automatically uses goo.gl, bit.ly, TinyURL, turl.ca (experimental) or is.gd to shorten all detected URLs in a player message.
author: vemacs
authors: [tuxed/minecrafter] 
website: http://dev.bukkit.org/server-mods/shortify/